name: 17 - 1 - Custom Actions - Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Target environment
        type: choice
        options: [dev, prod]
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}
# env:
#   working-directory: react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
      
