name: 17 - 2 - Using Custom JS Actions
on: 
  workflow_dispatch:
    inputs:
      base-branch: 
        description: Base branch for dependency update checks
        required: false
        default: main
      target-branch: 
        description: Target branch for creating the PR
        required: false
        default: update-dependencies
      working-dir:
        description: Working directory of the project
        required: true
        default: ./react-app
      debug:
        description: Enable debug messages
        required: false
        default: 'false'
run-name: Base ${{ inputs.base-branch }} -> Target ${{ inputs.target-branch }} | ${{ inputs.working-dir }}
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run JS Dependency Update Action
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-dir }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ inputs.debug }}
