name: 18 - 2 - Reusable Workflows - Caller Definition
on:
    workflow_dispatch:
jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yaml
        with:
            target-directory: 'production'
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print Outputs
              run: |
                  echo "Build Status: ${{ needs.deploy.outputs.build-status }}"
                  echo "Deployed URL: ${{ needs.deploy.outputs.url }}"